# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  # Simple text replacement
  - trigger: ";espanso"
    replace: "Hi there!"

  # Print the current date
  - trigger: ";now"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%H:%M"

  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - label: "[c]ode [b]lock [c]lip[b]oard"
    trigger: ";cb"
    replace: |
      ```
      {{cb}}
      ```
    vars:
      - name: "cb"
        type: "clipboard"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
