# [".vim/autoload/plug.vim"]
# type = "file"
# url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
# refreshPeriod = "168h"
#
# [".zgenom"]
#     type = "git-repo"
#     url = "https://github.com/jandamm/zgenom.git"
#     exact = true
#     refreshPeriod = "48h"
#
# [".tmux/plugins/tpm"]
#     type = "git-repo"
#     url = "https://github.com/tmux-plugins/tpm"
#     refreshPeriod = "168h"

[".config/awesome/bling"]
type = "git-repo"
url = "https://github.com/BlingCorp/bling.git"
refreshPeriod = "168h"
