#!/bin/sh

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
gsettings set org.gnome.desktop.interface gtk-theme 'Breeze'
gsettings set org.gnome.desktop.interface icon-theme 'Breeze'
gsettings set org.gnome.desktop.wm.preferences theme 'Breeze'

