#!/bin/sh

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
# gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-Light'
# gsettings set org.gnome.desktop.interface icon-theme 'WhiteSur-Light'
# gsettings set org.gnome.desktop.wm.preferences theme 'WhiteSur-Light'

