#!/bin/sh

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'
gsettings set org.gnome.desktop.interface icon-theme 'Breeze-Dark'
gsettings set org.gnome.desktop.wm.preferences theme 'Breeze-Dark'

